# Generated by Django 4.2.14 on 2024-07-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='productId',
            field=models.CharField(default='', max_length=100, verbose_name='Product Name'),
        ),
    ]
