# Generated by Django 4.2.14 on 2024-07-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styling', '0002_photos_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='styling',
            name='photo',
            field=models.ManyToManyField(to='styling.photos'),
        ),
    ]
