# Generated by Django 4.2.14 on 2024-07-10 14:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(max_length=100, verbose_name='Competition Name')),
                ('date_started', models.DateTimeField()),
                ('date_ended', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('no_of_votes', models.BigIntegerField(default=0)),
                ('design_image', models.ImageField(upload_to='', verbose_name='designs')),
                ('wishlist_no', models.BigIntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('competition_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divas.competitionname')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Name')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divas.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divas.submission')),
            ],
            options={
                'unique_together': {('username', 'post')},
            },
        ),
    ]
