# Generated by Django 4.2.14 on 2024-07-12 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('divas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community_forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented_by', models.CharField(max_length=100, verbose_name='Commented By')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='submission',
            name='design_image',
            field=models.ImageField(upload_to='images/', verbose_name='designs'),
        ),
    ]
