# Generated by Django 4.2.14 on 2024-07-12 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divas', '0003_users_alter_community_forum_commented_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='divas.users'),
        ),
    ]
